# Generated by Django 4.0.3 on 2022-07-30 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_file_notice_file1_notice_file2_notice_file3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='Published_Date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='Update_Date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
