# Generated by Django 4.0.3 on 2022-07-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_notice_published_date_alter_notice_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='File1',
            new_name='file1',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='File2',
            new_name='file2',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='File3',
            new_name='file3',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='File5',
            new_name='file5',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='Notice_Title',
            new_name='noticeTitle',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='Published_Date',
            new_name='published_Date',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='Update_Date',
            new_name='update_Date',
        ),
    ]
