# Generated by Django 4.0.3 on 2022-07-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_description_notice_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='File4',
            new_name='file4',
        ),
    ]
