# Generated by Django 4.0.3 on 2022-07-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_noticetitle_notice_notice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_Title',
            new_name='noticeTitle',
        ),
    ]
