# Generated by Django 4.0.3 on 2022-07-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_notice_file5'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desciption', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
