# Generated by Django 4.0.3 on 2022-07-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_facilities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='news & notice'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='news & notice'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='news & notice'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='news & notice'),
        ),
    ]
