# Generated by Django 4.0.3 on 2022-08-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_gallery_schoolmanagementcommittee_teacherandstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherandstaff',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
