# Generated by Django 4.0.3 on 2022-08-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_teacherandstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmanagementcommittee',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherandstaff',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
