# Generated by Django 4.0.3 on 2022-08-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_schoolmanagementcommittee_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentsview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additionalDetail', models.CharField(max_length=55)),
                ('studentView', models.TextField()),
                ('image', models.ImageField(upload_to='facilities')),
            ],
        ),
    ]
