# Generated by Django 4.0.3 on 2022-08-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_studentsview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmanagementcommittee',
            name='post',
            field=models.CharField(choices=[('Chairperson', 'Chairperson'), ('Secretary', 'Secretary'), ('Member', 'Member')], max_length=15),
        ),
        migrations.AlterField(
            model_name='teacherandstaff',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
