# Generated by Django 4.0.3 on 2022-08-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_teacherandstaff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmanagementcommittee',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
